/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface": "#fbf9f8",
                "error": "#ba1a1a",
                "outline": "#6e797b",
                "background": "#fbf9f8",
                "on-tertiary-fixed": "#002204",
                "on-surface": "#1b1c1c",
                "surface-variant": "#e3e2e2",
                "primary-fixed-dim": "#8ad2e0",
                "surface-container-high": "#e9e8e7",
                "inverse-surface": "#303030",
                "secondary": "#755b00",
                "tertiary-container": "#006519",
                "on-primary-fixed": "#001f25",
                "on-primary-fixed-variant": "#004e59",
                "primary-fixed": "#a6eefd",
                "on-tertiary": "#ffffff",
                "secondary-container": "#fed665",
                "on-error-container": "#93000a",
                "inverse-primary": "#8ad2e0",
                "on-error": "#ffffff",
                "secondary-fixed-dim": "#e9c254",
                "on-tertiary-fixed-variant": "#005313",
                "surface-container-highest": "#e3e2e2",
                "primary-container": "#00606d",
                "on-primary-container": "#91d8e7",
                "on-secondary": "#ffffff",
                "secondary-fixed": "#ffe08e",
                "surface-tint": "#136875",
                "tertiary-fixed": "#9ef799",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#83da7f",
                "outline-variant": "#bec8cb",
                "surface-container": "#efeded",
                "primary": "#004751",
                "on-surface-variant": "#3e484b",
                "on-primary": "#ffffff",
                "surface-bright": "#fbf9f8",
                "on-secondary-container": "#755c00",
                "inverse-on-surface": "#f2f0f0",
                "surface-container-low": "#f5f3f3",
                "tertiary": "#004a10",
                "on-background": "#1b1c1c",
                "on-secondary-fixed": "#241a00",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed-variant": "#584400"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "margin-desktop": "40px",
                "container-max": "1200px",
                "margin-mobile": "16px",
                "gutter": "24px",
                "base": "8px"
            },
            fontFamily: {
                "label-sm": ["Manrope"],
                "headline-xl": ["Manrope"],
                "body-md": ["Manrope"],
                "headline-md": ["Manrope"],
                "headline-lg": ["Manrope"],
                "label-md": ["Manrope"],
                "body-lg": ["Manrope"],
                "headline-lg-mobile": ["Manrope"]
            },
            fontSize: {
                "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
                "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }]
            }
        },
    },
    plugins: [],
};